name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x] # Using stable LTS version

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test
        
      - name: Build application
        run: npm run build

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push Docker image
        run: |
          docker build . -t savinder727/next.js-app:latest
          echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
          docker push savinder727/next.js-app:latest
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull savinder727/next.js-app:latest
            
            # Stop the existing container
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            
            # Start the new container
            docker run -d \
              --name nextjs-app \
              -p 3000:3000 \
              --restart unless-stopped \
              --network nginx-network \
              savinder727/next.js-app:latest
            
            # Reload Nginx
            sudo systemctl reload nginx